const products = [
  {
    name: "Motherboard",
    photo: "images/Motherboard.webp",
    price: "$323.98",
    detail: "Quantity: 100",
    description:
      "A motherboard, also known as the mainboard, is the central circuit board in a computer that connects key components such as the CPU, RAM, and expansion cards. It provides power and data pathways for these components and offers ports for external devices and peripherals.",
  },
  {
    name: "Processor (CPU)",
    photo: "images/CPU.webp",
    price: "$250.00",
    detail: "Quantity: 57",
    description:
      "The processor, or CPU (Central Processing Unit), is the primary component of a computer responsible for executing instructions and performing calculations. It acts as the brain of the computer, controlling and coordinating tasks, managing data flow, and executing programs.",
  },
  {
    name: "Memory (RAM)",
    photo: "images/RAM.webp",
    price: "$100.00",
    detail: "Quantity: 47",
    description:
      "Memory, or RAM (Random Access Memory), is a type of computer memory that provides fast, temporary storage for data that the CPU needs to access quickly. RAM allows for efficient multitasking and speedy data retrieval, which enhances the performance of applications and the overall system.",
  },
  {
    name: "Storage (SSD)",
    photo: "images/SSD.webp",
    price: "$175.00",
    detail: "Quantity: 37",
    description:
      "Storage, specifically SSD (Solid State Drive), is a data storage device that uses flash memory to store data persistently. It offers faster read and write speeds compared to traditional hard drives, improving the overall system performance and reducing load times for applications and operating systems.",
  },
  {
    name: "Case (Chassis)",
    photo: "images/Case.webp",
    price: "$79.99",
    detail: "Quantity: 29",
    description:
      "The case, or chassis, is the enclosure that houses and protects the internal components of a computer, such as the motherboard, CPU, RAM, and storage devices. It also provides ventilation and cooling to keep the components at optimal temperatures, along with space for cable management and expansion slots for peripherals.",
  },
  {
    name: "Fans (Cooling)",
    photo: "images/Fans.webp",
    price: "$40.00",
    detail: "Quantity: 59",
    description:
      "Fans are devices used in a computer to help maintain optimal temperatures by dissipating heat generated by components such as the CPU, GPU, and power supply. They improve airflow within the case, preventing overheating and ensuring stable performance and longevity of the hardware.",
  },
  {
    name: "Power Supply",
    photo: "images/Power.webp",
    price: "$200.00",
    detail: "Quantity: 56",
    description:
      "The power supply, also known as a PSU (Power Supply Unit), converts electricity from an external source into a usable form for the computer's internal components. It distributes power to the motherboard, CPU, GPU, storage, and other peripherals, while also protecting the system from power fluctuations and surges.",
  },
  {
    name: "Monitor",
    photo: "images/Monitor.webp",
    price: "$199.99",
    detail: "Quantity: 48",
    description:
      "A monitor is a display screen that visually presents information from a computer. It allows users to interact with and view content such as applications, images, and videos, and comes in various types such as LCD, LED, and OLED, offering different resolutions and display technologies.",
  },
  {
    name: "Keyboard",
    photo: "images/Keyboard.webp",
    price: "$60.00",
    detail: "Quantity: 24",
    description:
      "A keyboard is an input device used to type text and commands into a computer. It features keys arranged in a layout for typing letters, numbers, and symbols, as well as function keys for performing specific tasks and navigation keys for controlling the cursor.",
  },
  {
    name: "Mouse",
    photo: "images/Mouse.webp",
    price: "$39.99",
    detail: "Quantity: 55",
    description:
      "A mouse is a handheld input device that allows users to navigate and interact with a computer's graphical user interface. It uses buttons and a scroll wheel for clicking, dragging, and scrolling, providing a precise and efficient way to control the cursor and access various functions.",
  },
];

document.addEventListener("DOMContentLoaded", function () {
  const productModal = document.getElementById("productModal");
  const closeModal = document.getElementById("closeModal");

  const modalTitle = document.getElementById("modalTitle");
  const modalImage = document.getElementById("modalImage");
  const modalDescription = document.getElementById("modalDescription");
  const modalPrice = document.getElementById("modalPrice");

  const openModal = (product) => {
    modalTitle.textContent = product.name;
    modalImage.src = product.photo;
    modalImage.alt = product.name;
    modalDescription.textContent = product.detail;
    modalPrice.textContent = `Price: ${product.price}`;
    productModal.style.display = "block";
    modalDescription.textContent = product.description;
  };

  closeModal.addEventListener("click", function () {
    productModal.style.display = "none";
  });

  const container = document.querySelector(".product-container");

  products.forEach((product) => {
    const card = document.createElement("div");
    card.classList.add("product-card");

    const image = document.createElement("img");
    image.src = product.photo;
    image.alt = product.name;

    const name = document.createElement("h2");
    name.textContent = product.name;

    const price = document.createElement("p");
    price.textContent = `Price: ${product.price}`;

    const detail = document.createElement("p");
    detail.textContent = product.detail;

    card.appendChild(image);
    card.appendChild(name);
    card.appendChild(price);
    card.appendChild(detail);
    container.appendChild(card);

    card.addEventListener("click", function () {
      openModal(product);
    });
  });
});
